---
name: CI pipeline
on:
  push:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src/'
    container:
      image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Run ruff
        run: uvx ruff check .

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/uv-docker-example:${{ github.sha }}
  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    container:
      image: ghcr.io/${{ github.repository_owner }}/uv-docker-example:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Run tests
        run: |
          pytest /home/uv-example-user/src/tests
